name: Cargo lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  # Not needed in CI, should make things a bit faster
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  # Remove unnecessary WASM build artifacts
  WASM_BUILD_CLEAN_TARGET: 1
  # Stripping symbols and optimizing for binary size
  RUSTFLAGS: -C strip=symbols -C opt-level=s

jobs:
  lint-and-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: 🚧 Checkout project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: ⚙️ Install rust compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libudev-dev

      - name: 👨‍🔧 Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: 20

      - name: 🦿 Install Rust tookchain
        uses: dtolnay/rust-toolchain@c82636ac6f859942c6f571692f3880cf1d0fc5b0 # 1.83.0
        with:
          components: rustfmt, clippy

      - name: 🧠 Cache Rust dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: 🧭 Run cargo lint
        run: cargo fmt -- --check && cargo clippy -- -D warnings
