name: Cargo lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  # Not needed in CI, should make things a bit faster
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  # Remove unnecessary WASM build artifacts
  WASM_BUILD_CLEAN_TARGET: 1
  # Stripping symbols and optimizing for binary size
  RUSTFLAGS: -C strip=symbols -C opt-level=s

jobs:
  lint-and-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: 🚧 Checkout project
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: ⚙️ Install rust compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libudev-dev

      - name: 👨‍🔧 Install Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 20

      - name: 🦿 Install Rust tookchain
        uses: dtolnay/rust-toolchain@c82636ac6f859942c6f571692f3880cf1d0fc5b0 # 1.83.0
        with:
          components: rustfmt, clippy

      - name: 🧠 Cache Rust dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: 🧭 Run cargo lint
        run: cargo fmt -- --check && cargo clippy -- -D warnings
